# Generated by Django 4.0.5 on 2022-06-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadio',
            name='capacidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
